name: lg_ui_demo
description: Flutter demo to show how to code from Figma wireframes
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Inter
      fonts:
        - asset: fonts/Inter-Regular.ttf
          style: normal
        - asset: fonts/Inter-SemiBold.ttf
          weight: 500
        - asset: fonts/Inter-Bold.ttf
          weight: 600

